### ISSUE TITLE
[question] where in the code is the cap of 100 to some things

### ISSUE THREAD

**Issue by krispyking24** [maddie480/ExtendedVariantMode#49]
in short, i want to remove the cap/how high the setting can go for example max fall speed, gravity ect

**Comment by maddie480** [comment]
The scales are here if you want to mess with them in the code: https://github.com/maddie480/ExtendedVariantMode/blob/master/UI/ModOptionsEntries.cs#L56

But you can also edit `modsettings-ExtendedVariantMode.celeste` to set the values you want ^^

**Comment by krispyking24** [comment]
ok thank you for the assistance
